#!/bin/bash
# 
# Wrapper on /sbin/shutdown in order to make sure
# the webserver and all services are shutdown nicely
# before we really shutdown the sytstem
#


SDIR=/R1/webserConfig


error_exit(){
echo "$0 : ERROR : found problems when shutting down : $1 "
exit 1
}

shutdown_webserver(){
{ $SDIR/mysql_db stop || error_exit mysql ;} && { $SDIR/resources stop all || error_exit resources ;} && sleep 3 && { /usr/sbin/apache2ctl stop || error_exit apache ;} && exit 
echo "ERROR: webserver shutdown didn't complete successfully"
exit 1
}

shutdown_webserver && /sbin/shutdown $@

